---
all:
  children:
    vpn:
      hosts:
        outside:
          ansible_host: bouncer.oddbit.com
          ansible_user: root
        madhatter:
        inside:
          ansible_host: localhost
          ansible_port: 2200
          ansible_user: root
